FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat curl pnpm

ENV PNPM_HOME=/pnpm/store
RUN mkdir -p /pnpm/store && chown -R node:node /pnpm

COPY package.json pnpm-lock.yaml ./
RUN chown node:node /app
USER node
RUN pnpm install --frozen-lockfile
USER root

COPY . .

RUN chown -R node:node /app

USER node

EXPOSE 4000

CMD ["pnpm", "run", "start:dev"]
