FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat curl

COPY package*.json ./

RUN npm ci

COPY . .

RUN chown -R node:node /app

USER node

EXPOSE 4000

CMD ["npm", "run", "start:dev"]
