FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache pnpm

ENV PNPM_HOME=/pnpm/store

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--host"]
